Refactored ResultKind and selections
yankeeinlondon/scraped pull request #4
Opened 2022-02-24 18:11 UTC by yankeeinlondon

- removed the `Selection` struct as it better just to use **serde_json**'s Value enum
- removed the entire "elements" module as the usage of Value no longer necessitates its existance
- refactored `ResultKind::get()` method to adapt to the new data structures
- CLI now uses the refactored library code to produce a valid "title" property

2022-02-24 20:52 UTC, FabianLars requested changes
Nothing major 👍 Also nothing that actually _needs_ to be changed :)

2022-02-24 20:52 UTC, FabianLars commented on cli/src/show.rs
>  pub fn show(doc: &ParsedDoc, show: &Option<String>) -> Result<()> {
I can't add the comment on the correct line, but `","` on line 9 should be a char instead `','`.

Also, this function doesn't need to return a result as there are no possible errors, but i think i'd leave it as it is 🤔

2022-02-24 20:52 UTC, FabianLars commented on lib/src/results.rs
>      }
I hate github for not allowing me to add comments anywhere, but you can remove the .to_string() call on line 29.

2022-02-24 20:52 UTC, FabianLars commented on lib/src/results.rs
> +                .into_iter()
```suggestion
        .iter()
```

2022-02-24 20:52 UTC, FabianLars commented on lib/src/results.rs
> +                .into_iter()
```suggestion
                .iter()
```
v == `&Vec` - Calling into_iter() on a reference is the same as doing iter() which is kinda confusing.

2022-02-24 20:52 UTC, FabianLars commented on lib/src/results.rs
> +            ResultKind::Property(v) => match v {
match expressions destructuring a single pattern can be `if let` instead

2022-02-24 20:52 UTC, FabianLars commented on lib/src/selection.rs
> +/// node and returns as a serde::Value enumeration
```suggestion
/// node and returns as a [`serde::Value`] enumeration
```

2022-02-24 20:52 UTC, FabianLars commented on lib/src/selection.rs
> +    if text.len() > 0 {
```suggestion
    if !text.is_empty() {
```

2022-02-24 20:52 UTC, FabianLars commented on lib/src/selection.rs
> +            if href.len() == 0 {
```suggestion
            if href.is_empty() {
```

2022-02-24 20:52 UTC, FabianLars commented on lib/src/selection.rs
> +        let ext = src.split(".").last();
```suggestion
        let ext = src.split('.').last();
```
char instead of string is enough

2022-02-24 20:52 UTC, FabianLars commented on lib/src/selection.rs
> +            if (tag == "img".to_string()) || (is_image_format) {
```suggestion
            if (tag == "img") || (is_image_format) {
```
String implements `PartialEq<&str>` so no need to convert "img" to a String just for comparison.

2022-02-24 20:52 UTC, FabianLars commented on lib/src/util.rs
>  pub fn url_to_string<S>(url: &Url, serializer: S) -> Result<S::Ok, S::Error>
the url crate has a serde feature. may be worth to consider using that instead. Doesn't really matter and your way is probably lighter idk

2022-02-24 20:52 UTC, FabianLars commented on lib/src/util.rs
> +pub fn serialize_selection<S>(
Are the serialize_selection and serialize_selection_list functions really necessary? serde should be able to serialize HashMap, Vec, and Value just fine

2022-02-24 20:52 UTC, FabianLars commented on lib/src/lib.rs
>          trace!("getting the child URLs for {}", self.url);
Again the wrong line 😢 But on line 252 is a seemingly unnecessary to_string call

2022-02-24 20:52 UTC, FabianLars commented on lib/src/lib.rs
>      fn get_property_results(&self) -> Result<HashMap<String, Value>> {
Doesn't really need to return a Result

2022-02-24 20:52 UTC, FabianLars commented on lib/src/selection.rs
> +                    selection.insert(String::from("imageType"), json!(v.to_string()));
```suggestion
                    selection.insert(String::from("imageType"), json!(v));
```

2022-02-24 20:52 UTC, FabianLars commented on cli/src/main.rs
> +        let choices: Vec<&Value> = vec![&h1, &title]
```suggestion
        let choices: Vec<&Value> = [&h1, &title]
```

2022-02-25 17:47 UTC, yankeeinlondon commented on cli/src/show.rs
>  pub fn show(doc: &ParsedDoc, show: &Option<String>) -> Result<()> {
Ahhh I remember when you found something similar in my TODO app; I need to think in characters where I can. As for the Result<T> return type ... I thnk there may have been some String to URL parsing in this function earlier that is no longer here. Not sure but yeah there's zero reason to keep this if there's no potential for error.

2022-02-25 17:48 UTC, yankeeinlondon commented on lib/src/results.rs
>      }
I think us humans are going to go through a period of "half built AI" which thinks it's helping us by limiting our choices but actually getting in the way.

2022-02-25 17:51 UTC, yankeeinlondon commented on lib/src/results.rs
>      }
I removed the `.to_string()` but I also removed the simiilarly unnecessary `.to_clone()`

2022-02-25 17:53 UTC, yankeeinlondon commented on lib/src/results.rs
> +            ResultKind::Property(v) => match v {
I'm still getting my balance on which to use where but I presume `iter()` is more idiomatic unless you need `into_inter()` to avoid a dereference?

2022-02-25 17:54 UTC, yankeeinlondon commented on lib/src/util.rs
> +pub fn serialize_selection<S>(
these functions were necessary earlier but as I moved toward greater use of serde's value I may have removed their necessity. I do remember thinking I should check that.

2022-02-25 17:56 UTC, yankeeinlondon commented on lib/src/util.rs
> +pub fn serialize_selection<S>(
yeah 100% removable ... they're now gone.

2022-02-25 18:02 UTC, yankeeinlondon commented on cli/src/main.rs
> +        let choices: Vec<&Value> = vec![&h1, &title]
I did have this as a tuple to start but I was battling the borrow checker and somewhere in the mayhem this got switched. Glad to hear my initial instinct was correct.

2022-02-25 18:13 UTC, merged

2022-02-26 16:52 UTC, yankeeinlondon commented on lib/src/util.rs
>  pub fn url_to_string<S>(url: &Url, serializer: S) -> Result<S::Ok, S::Error>
I hadn't noticed that but I'll have a look later today

2022-02-26 16:53 UTC, yankeeinlondon commented on lib/src/util.rs
>  pub fn url_to_string<S>(url: &Url, serializer: S) -> Result<S::Ok, S::Error>
Side note ... I diagrammed out my overall processing flow and realized that there were other refactorings that would really open up the design goals so i'm 99% done with that now.

2022-02-26 16:54 UTC, yankeeinlondon commented
sorry i hadn't meant to start another review;